on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate feed.yml
        run: python generate-feed.py

      - name: Checkout other branch
        uses: actions/checkout@v4
        with:
          ref: generated-feed 
          path: 'generated-feed'

      - name: Copy feed.yml to other branch
        run: |
          cp out/feed.yml generated-feed/feed.yml

      - name: Commit and Push
        run: |
          cd generated-feed
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add feed.yml
          git commit -m "Update feed.yml" || echo "No changes to commit"
          git push origin HEAD:generated-feed
